addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    - jacoco.exec
    target_paths: 1a19b539-0097-4151-8a00-28cc30124dd0
  hosts:
  - node1
after_success:
- ' wget --content-disposition http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.7.201606060606/jacoco-0.7.7.201606060606.zip '
- ' unzip -o jacoco-0.7.7.201606060606.zip  '
- ' cd lib  '
- ' mv * ../  '
- ' cd ..  '
- ' chmod a+x *  '
- ' cd $PWD  '
- ' rm  ''jacoco.exec'''
- ' export JAVA_TOOL_OPTIONS=-javaagent:$PWD/jacocoagent.jar=destfile=$PWD/jacoco.exec,append=true  '
- ' travis_wait 720 mvn  test -Dmaven.test.failure.ignore=true -Djacoco.skip=true
  -Dcobertura.skip=true -Dmaven.clover.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true
  -Drat.ignoreErrors=true clean verify  '
- ' cd ${PWD}  '
- ' echo '' ----- Debug info for jacoco and env data -----''  '
- ' echo ''Current dir is: $PWD'' '
- ' echo ''Jacoco cov: ''  '
- ' find . -name ''*.exec''  '
- ' echo '' ----------------------------------------------'' '
- ./df-build.sh
before_install:
- rvm use 2.1.5 --install
- nvm install 0.12.2
- nvm use 0.12.2
branches: ''
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.rvm
  - $NVM_DIR
  - $HOME/.m2
env:
- MODULES=storm-core
- MODULES='!storm-core'
- MODULES='INTEGRATION-TEST'
install: /bin/bash ./dev-tools/travis/travis-install.sh `pwd`
jdk:
- oraclejdk8
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-dev.public-swarm.devfactory.com/travisWebHookListener?build_id=1a19b539-0097-4151-8a00-28cc30124dd0
script:
- /bin/bash ./dev-tools/travis/travis-script.sh `pwd` $MODULES
sudo: true
# Modified by Insights Service at 2016-11-27 19:25:49.084675
